# Generated by Django 5.0.6 on 2024-06-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=14)),
                ('nome_empresa', models.CharField(max_length=22)),
                ('segmento', models.CharField(max_length=22)),
                ('funcionarios', models.IntegerField()),
                ('faturamento', models.CharField(max_length=22)),
            ],
        ),
    ]
